import { useSession } from 'next-auth/react'
import Head from 'next/head'
import Link from 'next/link'
import { useContext } from 'react'
import { ToastContainer } from 'react-toastify'
import { Store } from '../utils/Store'
import 'react-toastify/dist/ReactToastify.css'

export default function Layout({ title, children }) {
  const { state } = useContext(Store)
  const { cart } = state
  const { status, data: session } = useSession()

  return (
    <>
      <Head>
        <title> {title ? title + ' - NextShop' : 'NextShop'} </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ToastContainer positinon="bottom-center" limit={1} />

      <div className="flex min-h-screen flex-col justify-between">
        <header>
          <nav className="flex flex-rowl h-12 items-center px-4 justify-between shadow-md bg-slate-200">
            <Link href="/" className="text-lg font-bold">
              Farruhni Web Dukoni
            </Link>
            <div>
              <Link href="/fortfolio" className="p-4">
                Fortfolio
              </Link>
              <Link href="/crypto" className="p-4">
                Crypto
              </Link>
            </div>
            <div>
              <Link href="/card" className="p-4">
                Card
                {cart.cartItems.length > 0 && (
                  <span className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs fond-bold text-white">
                    {cart.cartItems.reduce((a, c) => a + c.quantity, 0)}
                  </span>
                )}
              </Link>
              {status === 'loading' ? (
                'Loading'
              ) : session?.user ? (
                session.user.name
              ) : (
                <Link href="/login" className="p-4">
                  Login
                </Link>
              )}
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className="flex h-10 justify-center items-center  shadow-inner bg-red-300">
          <p>Copyight &copy; 2022 NextShop, Jaloliddin</p>
        </footer>
      </div>
    </>
  )
}
